/**
 * medienVerwaltungWeb.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookDTO { 
    isbn?: number;
    title?: string | null;
    description?: string | null;
    interpretFullName?: string | null;
    interpretId?: number;
    pageCount?: number;
    releaseYear?: number;
    location?: string | null;
}

