/**
 * medienVerwaltungWeb.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Song { 
    id?: number;
    title?: string | null;
    interpretFullName?: string | null;
    location?: string | null;
    length?: number;
    interpretId?: number
}

